# executable files for this directory
OBJECTS = add.exe whilecount.exe forcount.exe readdata.exe \
		  ifcount.exe add_item.exe add_item2.exe bookstore.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

add_item.exe add_item2.exe: Sales_item.h